# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "net7" ]
  pull_request:
    branches: [ "net7" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update versions
      env:
        VERSION_PREFIX: 5.0.0
        VERSION_SUFFIX: ${{github.run_number}}
      run: |
        VERSION=$VERSION_PREFIX.$VERSION_SUFFIX
        sed -i bak2 "s:<version>5.0.0</version>:<version>$VERSION</version>:g" .nuspec/Niramax.Forms.nuspec
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.101
    - name: Restore workloads
      run: dotnet workload restore Xamarin.Forms.Net.sln
    - name: Restore dependencies
      run: dotnet restore Xamarin.Forms.Net.sln
    - name: Build
      run: dotnet build --no-restore -c Release Xamarin.Forms.Net.sln
    - name: Pack
      run: nuget pack ./.nuspec/Niramax.Forms.nuspec
